version: '3.4'

services:
  cloudflarednsupdater:
    image: cloudflarednsupdater
    container_name: cloudflarednsupdater
    build:
      context: .
      dockerfile: CloudFlareDnsUpdater/Dockerfile
