version: '3.4'

services:
  cloudflarednsupdater:
    image: ghcr.io/trossr32/cloudflare-dns-updater
    container_name: cloudflarednsupdater
    build:
      context: .
      dockerfile: CloudFlareDnsUpdater/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

      # CloudFlare settings, use either Email and ApiKey or ApiToken
      - CloudFlare__Email=
      - CloudFlare__ApiKey=
      - CloudFlare__ApiToken=
      
      - UpdateIntervalSeconds=
      - LimitToZoneByDomain=
    restart: unless-stopped

