version: '3.4'

services:
  cloudflarednsupdater:
    image: cloudflarednsupdater
    container_name: cloudflarednsupdater
    build:
      context: .
      dockerfile: CloudFlareDnsUpdater/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CloudFlare__Email=
      - CloudFlare__ApiKey=
      - CloudFlare__ApiToken=
    restart: unless-stopped

