name: Build docker image
on:
  push:
    branches: [ master ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v4
      name: Build & push Docker image
      with:
        image: ghcr.io/trossr32/cloudflare-dns-updater
        tag: latest
        registry: ghcr.io
        dockerfile: CloudFlareDnsUpdater/Dockerfile
        username: trossr32
        password: ${{ secrets.REPOSNAPSHOT_API_KEY }}