name: Outdated package checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master ]
  
  workflow_dispatch:

env:
  SOLUTION_PATH: 'CloudFlareDnsUpdater.sln'
  EXCLUDE_PACKAGES: 'Microsoft.VisualStudio.Azure.Containers.Tools.Targets'

jobs:
  outdated-packages-check:
    runs-on: ubuntu-latest

    steps:
      - uses: trossr32/outdated-packages-action@v1.6.0
        with:
          use-dotnet-outdated: true
          dotnet-solution-or-project-path: ${{ env.SOLUTION_PATH }}
          dotnet-exclude-packages: ${{ env.EXCLUDE_PACKAGES }}